# Generated by Django 6.0.8 on 2026-09-27 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dicom_handler', '0056_dicomseries_station_name'),
        ('spatial_overlap', '0006_comparisonresult_slice_wise_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IntensityRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_type', models.CharField(choices=[('STRUCTURE', 'Structure'), ('IMAGE', 'Full image'), ('BOUNDARY', 'Boundary structure')], max_length=20)),
                ('seed_roi', models.CharField(blank=True, max_length=256, null=True)),
                ('boundary_roi', models.CharField(blank=True, max_length=256, null=True)),
                ('modality_hint', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('rule_type', models.CharField(choices=[('BOOLEAN', 'Boolean Expression'), ('INTENSITY', 'Intensity Range'), ('MARGIN', 'Margin'), ('CROP', 'Crop to Boundary'), ('CLEANUP', 'Cleanup / Refinement')], max_length=20)),
                ('name', models.CharField(help_text='Output ROI name. Must be unique within the RTStruct or will be replaced/renamed.', max_length=16)),
                ('output_action', models.CharField(choices=[('CREATE_NEW', 'Create new ROI'), ('REPLACE_EXISTING', 'Replace existing ROI')], default='CREATE_NEW', max_length=20)),
                ('output_color', models.CharField(blank=True, help_text="DICOM color string e.g. '255\\0\\0'. Defaults to yellow if blank.", max_length=64, null=True)),
                ('output_roi_type', models.CharField(blank=True, choices=[('EXTERNAL', 'EXTERNAL'), ('PTV', 'PTV'), ('CTV', 'CTV'), ('GTV', 'GTV'), ('TREATED_VOLUME', 'TREATED_VOLUME'), ('IRRAD_VOLUME', 'IRRAD_VOLUME'), ('OAR', 'OAR'), ('BOLUS', 'BOLUS'), ('AVOIDANCE', 'AVOIDANCE'), ('ORGAN', 'ORGAN'), ('MARKER', 'MARKER'), ('REGISTRATION', 'REGISTRATION'), ('ISOCENTER', 'ISOCENTER'), ('CONTRAST_AGENT', 'CONTRAST_AGENT'), ('CAVITY', 'CAVITY'), ('BRACHY_CHANNEL', 'BRACHY_CHANNEL'), ('BRACHY_ACCESSORY', 'BRACHY_ACCESSORY'), ('BRACHY_SRC_APP', 'BRACHY_SRC_APP'), ('BRACHY_CHNL_SHLD', 'BRACHY_CHNL_SHLD'), ('SUPPORT', 'SUPPORT'), ('FIXATION', 'FIXATION'), ('DOSE_REGION', 'DOSE_REGION'), ('CONTROL', 'CONTROL'), ('DOSE_MEASUREMENT', 'DOSE_MEASUREMENT')], default='ORGAN', max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['pipeline', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CropBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_roi', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundaries', to='rule_based_segmentation.cropruleconfig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='IntensityRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intensity_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='rule_based_segmentation.intensityruleconfig')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MarginRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('UNIFORM', 'Uniform'), ('ANISOTROPIC', 'Anisotropic')], max_length=20)),
                ('source', models.CharField(max_length=256)),
                ('margin_mm', models.FloatField(blank=True, null=True)),
                ('margin_x_mm', models.FloatField(blank=True, null=True)),
                ('margin_y_mm', models.FloatField(blank=True, null=True)),
                ('margin_z_mm', models.FloatField(blank=True, null=True)),
                ('kernel_type', models.CharField(blank=True, choices=[('ball', 'Ball'), ('box', 'Box'), ('cross', 'Cross')], default='ball', max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_rule', models.OneToOneField(limit_choices_to={'rule_type': 'MARGIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='margin_config', to='rule_based_segmentation.pipelinerule')),
            ],
        ),
        migrations.AddField(
            model_name='intensityruleconfig',
            name='pipeline_rule',
            field=models.OneToOneField(limit_choices_to={'rule_type': 'INTENSITY'}, on_delete=django.db.models.deletion.CASCADE, related_name='intensity_config', to='rule_based_segmentation.pipelinerule'),
        ),
        migrations.AddField(
            model_name='cropruleconfig',
            name='pipeline_rule',
            field=models.OneToOneField(limit_choices_to={'rule_type': 'CROP'}, on_delete=django.db.models.deletion.CASCADE, related_name='crop_config', to='rule_based_segmentation.pipelinerule'),
        ),
        migrations.CreateModel(
            name='CleanupRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('SMOOTH_STRUCTURE', 'Smooth Surface'), ('GAUSSIAN_SMOOTH', 'Gaussian Smooth'), ('FILL_HOLES', 'Fill Holes'), ('REMOVE_SMALL_COMPONENTS', 'Remove Small Components'), ('KEEP_LARGEST_COMPONENT', 'Keep Largest Component')], max_length=30)),
                ('source', models.CharField(max_length=256)),
                ('smoothing_mm', models.FloatField(blank=True, null=True)),
                ('iterations', models.PositiveIntegerField(blank=True, null=True)),
                ('min_size_mm3', models.FloatField(blank=True, null=True)),
                ('fully_connected', models.BooleanField(blank=True, null=True)),
                ('sigma_mm', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_rule', models.OneToOneField(limit_choices_to={'rule_type': 'CLEANUP'}, on_delete=django.db.models.deletion.CASCADE, related_name='cleanup_config', to='rule_based_segmentation.pipelinerule')),
            ],
        ),
        migrations.CreateModel(
            name='BooleanExpressionNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('OPERATION', 'Operation'), ('ROI', 'ROI Reference')], max_length=20)),
                ('operation_type', models.CharField(blank=True, choices=[('UNION', 'Union'), ('INTERSECTION', 'Intersection'), ('SUBTRACT', 'Subtract'), ('XOR', 'Exclusive OR')], max_length=20, null=True)),
                ('roi_name', models.CharField(blank=True, max_length=256, null=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rule_based_segmentation.booleanexpressionnode')),
                ('pipeline_rule', models.ForeignKey(limit_choices_to={'rule_type': 'BOOLEAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='boolean_nodes', to='rule_based_segmentation.pipelinerule')),
            ],
            options={
                'ordering': ['pipeline_rule', 'parent__isnull', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SegmentationPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Pipeline template name', max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Public pipelines are visible to all authenticated users.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pipelines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_public_pipeline', 'Can view public pipelines')],
            },
        ),
        migrations.CreateModel(
            name='SegmentationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('UPLOAD', 'Uploaded RTStruct'), ('IMPORT', 'Auto-segmented RTStructureFileImport')], max_length=10)),
                ('output_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('backup_file_path', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dicom_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentation_jobs', to='dicom_handler.dicomseries')),
                ('input_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentation_jobs', to='dicom_handler.rtstructurefileimport')),
                ('input_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segmentation_jobs', to='spatial_overlap.rtstructuresetfile')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='rule_based_segmentation.segmentationpipeline')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pipelinerule',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rule_based_segmentation.segmentationpipeline'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinerule',
            unique_together={('pipeline', 'order')},
        ),
    ]
