# Generated by Django 6.0.8 on 2026-09-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule_based_segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booleanexpressionnode',
            options={'ordering': ['pipeline_rule', 'order']},
        ),
    ]
