# Generated by Django 5.2.6 on 2025-09-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0002_alter_autosegmentationtemplate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='bearer_token_validaty',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
