# Generated by Django 5.2.6 on 2025-09-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0003_systemconfiguration_bearer_token_validaty'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='associated_autosegmentation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.autosegmentationtemplate'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='data_pull_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
