# Generated by Django 5.2.6 on 2025-09-13 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0004_ruleset_associated_autosegmentation_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosegmentationtemplate',
            name='template_file_checksum',
        ),
        migrations.RemoveField(
            model_name='autosegmentationtemplate',
            name='template_file_path',
        ),
        migrations.AddField(
            model_name='dicomfileexport',
            name='server_segmentation_file_transaction_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='draw_base_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseries',
            name='series_processsing_status',
            field=models.CharField(blank=True, choices=[('UNPROCESSED', 'Unprocessed'), ('RULE_MATCHED', 'Rule Matched'), ('RULE_NOT_MATCHED', 'Rule Not Matched'), ('MULTIPLE_RULES_MATCHED', 'Multiple Rules Matched'), ('DEIDENTIFIED_SUCCESSFULLY', 'Deidentified Successfully'), ('DEIDENTIFICATION_FAILED', 'Deidentification Failed'), ('PENDING_TRANSFER_TO_DRAW_SERVER', 'Pending Transfer to Draw Server'), ('SENT_TO_DRAW_SERVER', 'Sent to Draw Server'), ('RTSTRUCTURE_RECEIVED', 'RT Structure Received'), ('RTSTRUCTURE_EXPORTED', 'RT Structure Exported'), ('RTSTRUCTURE_EXPORT_FAILED', 'RT Structure Export Failed')], default='UNPROCESSED', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='operator_type',
            field=models.CharField(choices=[('EQUALS', 'Equals'), ('NOT_EQUALS', 'Not Equals'), ('GREATER_THAN', 'Greater Than'), ('LESS_THAN', 'Less Than'), ('GREATER_THAN_OR_EQUAL_TO', 'Greater Than Or Equal To'), ('LESS_THAN_OR_EQUAL_TO', 'Less Than Or Equal To'), ('CASE_SENSITIVE_STRING_CONTAINS', 'Case Sensitive String Contains'), ('CASE_INSENSITIVE_STRING_CONTAINS', 'Case Insensitive String Contains'), ('CASE_SENSITIVE_STRING_DOES_NOT_CONTAIN', 'Case Sensitive String Does Not Contain'), ('CASE_INSENSITIVE_STRING_DOES_NOT_CONTAIN', 'Case Insensitive String Does Not Contain'), ('CASE_SENSITIVE_STRING_EXACT_MATCH', 'Case Sensitive String Exact Match'), ('CASE_INSENSITIVE_STRING_EXACT_MATCH', 'Case Insensitive String Exact Match')], max_length=256),
        ),
        migrations.CreateModel(
            name='AutosegmentationModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('config', models.CharField(max_length=256)),
                ('trainer_name', models.CharField(max_length=256)),
                ('postprocess', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autosegmentation_template_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.autosegmentationtemplate')),
            ],
            options={
                'verbose_name': 'Autosegmentation Model',
                'verbose_name_plural': 'Autosegmentation Models',
            },
        ),
        migrations.CreateModel(
            name='AutosegmentationMappedStructure',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('map_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autosegmentation_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.autosegmentationmodel')),
            ],
            options={
                'verbose_name': 'Autosegmentation Mapped Structure',
                'verbose_name_plural': 'Autosegmentation Mapped Structures',
            },
        ),
    ]
