# Generated by Django 5.2.6 on 2025-09-13 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0005_remove_autosegmentationtemplate_template_file_checksum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autosegmentationmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='autosegmentationtemplate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dicomfileexport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dicominstance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dicomseries',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dicomstudy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dicomtagtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rtstructurefileimport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rule',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ruleset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='bearer_token_validaty',
            field=models.DateTimeField(blank=True, help_text='Bearer token validity for the DRAW API server', null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='data_pull_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Data pull start datetime for the DRAW API server', null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='draw_api_credentials',
            field=models.CharField(blank=True, help_text='Bearer token from the DRAW API server', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='draw_base_url',
            field=models.CharField(blank=True, default='https://draw.chavi.ai', help_text='Base URL of the DRAW API server', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='folder_configuration',
            field=models.CharField(blank=True, help_text='Full path of the DICOM folder from which DICOM data will be read and RT Structure file will be exported to', max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='AutosegmentationStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('map_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autosegmentation_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.autosegmentationmodel')),
            ],
            options={
                'verbose_name': 'Autosegmentation Mapped Structure',
                'verbose_name_plural': 'Autosegmentation Mapped Structures',
            },
        ),
        migrations.DeleteModel(
            name='AutosegmentationMappedStructure',
        ),
    ]
