# Generated by Django 5.2.6 on 2025-09-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0006_alter_autosegmentationmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomtagtype',
            options={'verbose_name': 'DICOM Tag Type', 'verbose_name_plural': 'DICOM Tag Types'},
        ),
    ]
