# Generated by Django 5.2.6 on 2025-09-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0008_alter_rule_dicom_tag_type_alter_rule_operator_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomtagtype',
            name='tag_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dicomtagtype',
            name='tag_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dicomtagtype',
            name='value_representation',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
