# Generated by Django 5.2.6 on 2025-09-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0010_auto_20250913_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemconfiguration',
            old_name='draw_api_credentials',
            new_name='draw_bearer_token',
        ),
        migrations.RenameField(
            model_name='systemconfiguration',
            old_name='bearer_token_validaty',
            new_name='draw_bearer_token_validaty',
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='client_id',
            field=models.CharField(blank=True, help_text='Client ID from the DRAW API server', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='draw_refresh_token',
            field=models.CharField(blank=True, help_text='Refresh token from the DRAW API server', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='draw_upload_endpoint',
            field=models.CharField(blank=True, default='https://draw.chavi.ai/api/upload/', help_text='Upload endpoint of the DRAW API server', max_length=256, null=True),
        ),
    ]
