# Generated by Django 5.2.6 on 2025-09-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0012_remove_dicomfileexport_server_segmentation_file_transaction_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomseries',
            name='series_processsing_status',
            field=models.CharField(blank=True, choices=[('UNPROCESSED', 'Unprocessed'), ('RULE_MATCHED', 'Rule Matched'), ('RULE_NOT_MATCHED', 'Rule Not Matched'), ('MULTIPLE_RULES_MATCHED', 'Multiple Rules Matched'), ('DEIDENTIFIED_SUCCESSFULLY', 'Deidentified Successfully'), ('DEIDENTIFICATION_FAILED', 'Deidentification Failed'), ('PENDING_TRANSFER_TO_DRAW_SERVER', 'Pending Transfer to Draw Server'), ('SENT_TO_DRAW_SERVER', 'Sent to Draw Server'), ('FAILED_TRANSFER_TO_DRAW_SERVER', 'Failed Transfer to Draw Server'), ('RTSTRUCTURE_RECEIVED', 'RT Structure Received'), ('RTSTRUCTURE_EXPORTED', 'RT Structure Exported'), ('RTSTRUCTURE_EXPORT_FAILED', 'RT Structure Export Failed')], default='UNPROCESSED', max_length=256, null=True),
        ),
    ]
