# Generated by Django 5.2.6 on 2025-09-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0013_alter_dicomseries_series_processsing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainExecutionLock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lock_name', models.CharField(help_text='Name of the lock', max_length=100, unique=True)),
                ('chain_id', models.CharField(help_text='Celery chain ID', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.CharField(help_text='Task or process that acquired the lock', max_length=100)),
                ('expires_at', models.DateTimeField(help_text='When this lock expires')),
                ('status', models.CharField(default='running', help_text='Chain execution status', max_length=50)),
            ],
            options={
                'verbose_name': 'Chain Execution Lock',
                'verbose_name_plural': 'Chain Execution Locks',
            },
        ),
    ]
