# Generated by Django 5.2.6 on 2025-09-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0014_chainexecutionlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfileexport',
            name='deidentified_zip_file_transfer_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CHEKSUM_MATCH_FAILED', 'Checksum match failed'), ('INVALID_RT_STRUCT_FILE', 'Invalid RTStructureSet FIle Received'), ('RTSTRUCT_RECEIVED', 'RTStructureSet File Received')], default='PENDING', help_text='Status of the zip file transfer to the DRAW API server', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='dicomseries',
            name='series_processsing_status',
            field=models.CharField(blank=True, choices=[('UNPROCESSED', 'Unprocessed'), ('RULE_MATCHED', 'Rule Matched'), ('RULE_NOT_MATCHED', 'Rule Not Matched'), ('MULTIPLE_RULES_MATCHED', 'Multiple Rules Matched'), ('DEIDENTIFIED_SUCCESSFULLY', 'Deidentified Successfully'), ('DEIDENTIFICATION_FAILED', 'Deidentification Failed'), ('PENDING_TRANSFER_TO_DRAW_SERVER', 'Pending Transfer to Draw Server'), ('SENT_TO_DRAW_SERVER', 'Sent to Draw Server'), ('FAILED_TRANSFER_TO_DRAW_SERVER', 'Failed Transfer to Draw Server'), ('INVALID_RTSTRUCTURE_RECEIVED', 'Invalid RT Structure Received'), ('RTSTRUCTURE_RECEIVED', 'RT Structure Received'), ('RTSTRUCTURE_EXPORTED', 'RT Structure Exported'), ('RTSTRUCTURE_EXPORT_FAILED', 'RT Structure Export Failed')], default='UNPROCESSED', max_length=256, null=True),
        ),
    ]
