# Generated by Django 5.2.6 on 2025-09-15 06:37

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0015_alter_dicomfileexport_deidentified_zip_file_transfer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='draw_bearer_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Bearer token from the DRAW API server', null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='draw_refresh_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Refresh token from the DRAW API server', null=True),
        ),
    ]
