# Generated by Django 5.2.6 on 2025-09-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0017_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='parameter_name',
            field=models.CharField(help_text='Name of the parameter', max_length=256),
        ),
    ]
