# Generated by Django 5.2.6 on 2025-09-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0018_alter_statistics_parameter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='series_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
