# Generated by Django 5.2.6 on 2025-09-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0019_dicomseries_series_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='folder_configuration',
            field=models.CharField(blank=True, default='/app/datastore', help_text='Full path of the DICOM folder from which DICOM data will be read and RT Structure file will be exported to', max_length=256, null=True),
        ),
    ]
