# Generated by Django 5.2.6 on 2025-09-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0020_alter_systemconfiguration_folder_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='client_id',
            field=models.CharField(blank=True, help_text='Client ID from the DRAW API server. Please rember this is case sensitive and should match what is entered in the server to ensure you can see the data for your center in the server.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='data_pull_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Data pull start datetime for the DRAW API server. The system will only copy DICOM data which has been created or modified after this date and time.', null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='folder_configuration',
            field=models.CharField(blank=True, default='/app/datastore', help_text='Full path of the DICOM folder from which DICOM data will be read and RT Structure file will be exported to. Use the default value if your application has been installed using docker.', max_length=256, null=True),
        ),
    ]
