# Generated by Django 5.2.6 on 2025-09-30 01:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0021_alter_systemconfiguration_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContourModificationTypeChoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modification_type', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contour Modification Type Choice',
                'verbose_name_plural': 'Contour Modification Type Choices',
            },
        ),
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='contour_modification_time_required',
            field=models.IntegerField(blank=True, help_text='Time required to modify the contours in this structure set in minutes. Please do not include time required to create or edit new structures which were not supposed to be autosegmented.', null=True),
        ),
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='date_contour_reviewed',
            field=models.DateField(blank=True, help_text='Date when the contour was reviewed', null=True),
        ),
        migrations.CreateModel(
            name='RTStructureFileVOIData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('volume_name', models.CharField(blank=True, help_text='Name of the volume', max_length=256, null=True)),
                ('assessor_name', models.CharField(blank=True, help_text='Name of the assessor who reviewed the volume', max_length=256, null=True)),
                ('contour_modification', models.CharField(blank=True, choices=[('NO_MODIFICATION', 'No Modification'), ('MAJOR_MODIFICATION', 'Major Modification'), ('MINOR_MODIFICATION', 'Minor Modification'), ('NOT_SEGMENTED', 'Not Segmented')], default='NO_MODIFICATION', help_text='Contour modification required. If the contour was blank choose Not Segmented.', max_length=256, null=True)),
                ('contour_modification_comments', models.TextField(blank=True, help_text='Comments about the contour modification.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contour_modification_type', models.ManyToManyField(blank=True, help_text='Type of contour modification. ', to='dicom_handler.contourmodificationtypechoices')),
                ('rt_structure_file_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.rtstructurefileimport')),
            ],
            options={
                'verbose_name': 'RT Structure File Void Data',
                'verbose_name_plural': 'RT Structure File Void Data',
            },
        ),
    ]
