# Generated by Django 5.2.6 on 2025-09-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0022_contourmodificationtypechoices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rtstructurefilevoidata',
            options={'verbose_name': 'RT Structure File VOI Data', 'verbose_name_plural': 'RT Structure File VOI Data'},
        ),
        migrations.RemoveField(
            model_name='rtstructurefilevoidata',
            name='assessor_name',
        ),
    ]
