# Generated by Django 5.2.6 on 2025-09-30 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0023_alter_rtstructurefilevoidata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='overall_rating',
            field=models.IntegerField(blank=True, default=5, help_text='Overall rating of the automatic segementation quality between 0 to 10 where 10 indicates an excellent quality and 0 the worst possible quality.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
