# Generated by Django 5.2.6 on 2025-09-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0024_rtstructurefileimport_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='assessor_name',
            field=models.CharField(blank=True, help_text='Name of the assessor who reviewed the contour', max_length=256, null=True),
        ),
    ]
