# Generated by Django 5.2.6 on 2025-09-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0025_rtstructurefileimport_assessor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtstructurefilevoidata',
            name='contour_modification_type',
            field=models.ManyToManyField(blank=True, help_text='Type of contour modification made. You can select multiple options here or leave blank if this is not applicable. To add a new type of modification please contact your Administrator. ', to='dicom_handler.contourmodificationtypechoices'),
        ),
    ]
