# Generated by Django 5.2.6 on 2025-10-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0027_contour_modification_type_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtstructurefilevoidata',
            name='contour_modification',
            field=models.CharField(blank=True, choices=[('NO_MODIFICATION', 'No Modification'), ('MAJOR_MODIFICATION', 'Major Modification'), ('MINOR_MODIFICATION', 'Minor Modification'), ('NOT_SEGMENTED', 'Not Segmented')], default='NO_MODIFICATION', help_text='Contour modification required. If the contour was blank choose Not Segmented. Note that the definiton of major modification can include scenarios where you had to completely redraw the structure, where there was significant risk of underdose to the target or overdose to the organs at risk due to error, and any modification in an axial plane exceeding 1 cm. Additionally any other criteria that you feel made you label this as major modification is also fine as long as that is documented in the comments. ', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='systemconfiguration',
            name='draw_base_url',
            field=models.CharField(blank=True, default='https://draw.chavi.ai/', help_text='Base URL of the DRAW API server', max_length=256, null=True),
        ),
    ]
