# Generated by Django 5.2.7 on 2025-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0028_alter_rtstructurefilevoidata_contour_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='series_files_fully_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dicomseries',
            name='series_files_fully_read_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
