# Generated by Django 5.2.7 on 2025-10-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0029_dicomseries_series_files_fully_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='draw_token_refresh_endpoint',
            field=models.CharField(blank=True, default='/api/token/refresh/', help_text='Token refresh endpoint of the DRAW API server where the refresh token is to be refreshed.', max_length=256, null=True),
        ),
    ]
