# Generated by Django 5.2.7 on 2025-10-21 10:25

import json
import os
from django.db import migrations
from django.conf import settings


def load_autosegmentation_templates(apps, schema_editor):
    """Load autosegmentation templates from JSON fixture file"""
    AutosegmentationTemplate = apps.get_model('dicom_handler', 'AutosegmentationTemplate')
    AutosegmentationModel = apps.get_model('dicom_handler', 'AutosegmentationModel')
    AutosegmentationStructure = apps.get_model('dicom_handler', 'AutosegmentationStructure')
    
    # Path to the JSON fixture file
    fixture_path = os.path.join(settings.BASE_DIR, 'seed_data', 'autosegmentation_templates.json')
    
    if not os.path.exists(fixture_path):
        print(f"Warning: Fixture file not found at {fixture_path}")
        return
    
    # Check if example templates already exist by UUID to avoid duplicates
    example_template_uuids = [
        "9e3cb026-4208-489b-af02-34a437719deb",  # Example Breast Template
        "99a29dc2-2ad4-41a4-aa83-6657cbb30b62",  # Example Head Neck Template
        "450058ba-a0fd-45e0-9756-9fb832269650",  # Example Prostate Template
        "3c51faad-914e-4c46-acff-a7ccb7e07fff",  # Example Lung Template
        "eb6a771a-821d-4c37-ae3c-bac1f1d1a2bd",  # Example Rectum Template
        "038493c6-1766-49ca-a4e6-749bee3a6a4d",  # Example CNS Template
        "a4a772ee-e872-4326-a7b8-0627b736228d",  # Example Gyn Template
    ]
    
    existing_examples = AutosegmentationTemplate.objects.filter(
        id__in=example_template_uuids
    ).count()
    
    if existing_examples > 0:
        print(f"Found {existing_examples} example templates already loaded. Skipping seed data load.")
        return
    
    with open(fixture_path, 'r', encoding='utf-8') as f:
        fixture_data = json.load(f)
    
    # Separate data by model type
    templates_data = [item for item in fixture_data if item['model'] == 'dicom_handler.autosegmentationtemplate']
    models_data = [item for item in fixture_data if item['model'] == 'dicom_handler.autosegmentationmodel']
    structures_data = [item for item in fixture_data if item['model'] == 'dicom_handler.autosegmentationstructure']
    
    # Create templates first
    template_map = {}
    for item in templates_data:
        template = AutosegmentationTemplate(
            id=item['pk'],
            template_name=item['fields']['template_name'],
            template_description=item['fields']['template_description']
        )
        template.save()
        template_map[item['pk']] = template
        print(f"Created template: {template.template_name}")
    
    # Create models
    model_map = {}
    for item in models_data:
        template_id = item['fields']['autosegmentation_template_name']
        model = AutosegmentationModel(
            id=item['pk'],
            autosegmentation_template_name=template_map.get(template_id),
            model_id=item['fields']['model_id'],
            name=item['fields']['name'],
            config=item['fields']['config'],
            trainer_name=item['fields']['trainer_name'],
            postprocess=item['fields']['postprocess']
        )
        model.save()
        model_map[item['pk']] = model
        print(f"Created model: {model.name}")
    
    # Create structures
    for item in structures_data:
        model_id = item['fields']['autosegmentation_model']
        structure = AutosegmentationStructure(
            id=item['pk'],
            autosegmentation_model=model_map.get(model_id),
            map_id=item['fields']['map_id'],
            name=item['fields']['name']
        )
        structure.save()
    
    print(f"Successfully loaded {len(templates_data)} templates, {len(models_data)} models, and {len(structures_data)} structures")


def reverse_load_autosegmentation_templates(apps, schema_editor):
    """Remove all autosegmentation templates, models, and structures"""
    AutosegmentationTemplate = apps.get_model('dicom_handler', 'AutosegmentationTemplate')
    AutosegmentationModel = apps.get_model('dicom_handler', 'AutosegmentationModel')
    AutosegmentationStructure = apps.get_model('dicom_handler', 'AutosegmentationStructure')
    
    AutosegmentationStructure.objects.all().delete()
    AutosegmentationModel.objects.all().delete()
    AutosegmentationTemplate.objects.all().delete()
    print("Removed all autosegmentation templates, models, and structures")


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0030_systemconfiguration_draw_token_refresh_endpoint'),
    ]

    operations = [
        migrations.RunPython(load_autosegmentation_templates, reverse_load_autosegmentation_templates),
    ]
