# Generated by Django 5.2.7 on 2025-10-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0031_load_autosegmentation_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
