# Generated by Django 5.2.7 on 2025-10-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0032_alter_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='study_date_based_filtering',
            field=models.BooleanField(default=False, help_text='If checked then during the DICOM export task, the system will filter out DICOM studies whose study dates are before the date set for the data_pull_start_datetime pull above.'),
        ),
    ]
