# Generated by Django 5.2.8 on 2025-11-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0033_systemconfiguration_study_date_based_filtering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='study_date_based_filtering',
            field=models.BooleanField(default=False, help_text='If checked then during the DICOM export task, the system will filter out DICOM studies whose study dates are before the date set for the Pull Start Date Time Field above. Note that this will read the DICOM metadata and retrive the study dates from the files.'),
        ),
    ]
