# Generated by Django 5.2.8 on 2025-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0034_alter_systemconfiguration_study_date_based_filtering'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_combination_type',
            field=models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', help_text='The rule combination type. This can be AND or OR. This defines how this rule should be combined with other rules in the ruleset.', max_length=256),
        ),
    ]
