# Generated by Django 5.2.8 on 2025-11-16 13:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0035_rule_rule_combination_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rulegroup_combination_type', models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', help_text='The rule group combination type. This can be AND or OR. This defines how this rule group should be combined with other rule groups in the ruleset.', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rule Group',
                'verbose_name_plural': 'Rule Groups',
            },
        ),
    ]
