# Generated by Django 5.2.8 on 2025-11-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0036_rulegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleset',
            name='rulegroup',
            field=models.ForeignKey(blank=True, help_text='The rule group to which this ruleset belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.rulegroup'),
        ),
    ]
