# Generated by Django 5.2.8 on 2025-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0037_ruleset_rulegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='rule_combination_type',
            field=models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', help_text='This defines how the ruleset will be combined with other rulesets in the rulegroup. This can be AND or OR.', max_length=256, verbose_name='Ruleset Combination Type'),
        ),
    ]
