# Generated by Django 5.2.8 on 2025-11-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0038_alter_ruleset_rule_combination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='rule_order',
            field=models.IntegerField(default=1, help_text='The order in which the rule will be evaluated.'),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='rulset_order',
            field=models.IntegerField(default=1, help_text='The order in which the ruleset will be evaluated.'),
        ),
    ]
