# Generated by Django 5.2.8 on 2025-11-16 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0039_rule_rule_order_ruleset_rulset_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegroup',
            name='associated_autosegmentation_template',
            field=models.ForeignKey(blank=True, help_text='The autosegmentation template associated with this rule group.', null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.autosegmentationtemplate'),
        ),
    ]
