# Generated by Django 5.2.8 on 2025-11-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0040_rulegroup_associated_autosegmentation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulegroup',
            name='rulegroup_name',
            field=models.CharField(default='Rule Group', help_text='The name of the rule group.', max_length=256),
        ),
    ]
