# Generated by Django 5.2.8 on 2025-11-16 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0041_rulegroup_rulegroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulegroup',
            name='rulegroup_combination_type',
        ),
    ]
