# Generated by Django 5.2.8 on 2025-11-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0042_remove_rulegroup_rulegroup_combination_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruleset',
            old_name='rule_combination_type',
            new_name='ruleset_combination_type',
        ),
    ]
