# Generated by Django 5.2.8 on 2025-11-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0043_rename_rule_combination_type_ruleset_ruleset_combination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='ruleset_combination_type',
            field=models.CharField(choices=[('AND', 'And'), ('OR', 'Or')], default='AND', help_text='This defines how the ruleset will be combined with other rulesets in the rulegroup. This can be AND or OR.', max_length=256, verbose_name='RuleSet Combination'),
        ),
    ]
