# Generated by Django 5.2.9 on 2026-01-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0044_alter_ruleset_ruleset_combination_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='accession_number',
            field=models.CharField(blank=True, help_text='Accession number for the study', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='deidentified_accession_number',
            field=models.CharField(blank=True, help_text='Deidentified accession number', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='deidentified_study_id',
            field=models.CharField(blank=True, help_text='Deidentified study ID', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='study_id',
            field=models.CharField(blank=True, help_text='Study ID', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='study_time',
            field=models.TimeField(blank=True, help_text='Time the study was performed', null=True),
        ),
    ]
