# Generated by Django 5.2.10 on 2026-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0045_dicomstudy_accession_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='reidentified_rt_structure_file_series_instance_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='reidentified_rt_structure_file_sop_class_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='reidentified_rt_structure_file_sop_instance_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='reidentified_rt_structure_file_study_instance_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
