# Generated by Django 5.2.10 on 2026-01-14 03:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0046_rtstructurefileimport_reidentified_rt_structure_file_series_instance_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureProperties',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roi_label', models.CharField(blank=True, max_length=256, null=True, verbose_name='Preferred Name for the Structure (ROI)')),
                ('rt_roi_interpreted_type', models.CharField(blank=True, choices=[('EXTERNAL', 'EXTERNAL'), ('PTV', 'PTV'), ('CTV', 'CTV'), ('GTV', 'GTV'), ('TREATED_VOLUME', 'TREATED_VOLUME'), ('IRRAD_VOLUME', 'IRRAD_VOLUME'), ('OAR', 'OAR'), ('BOLUS', 'BOLUS'), ('AVOIDANCE', 'AVOIDANCE'), ('ORGAN', 'ORGAN'), ('MARKER', 'MARKER'), ('REGISTRATION', 'REGISTRATION'), ('ISOCENTER', 'ISOCENTER'), ('CONTRAST_AGENT', 'CONTRAST_AGENT'), ('CAVITY', 'CAVITY'), ('BRACHY_CHANNEL', 'BRACHY_CHANNEL'), ('BRACHY_ACCESSORY', 'BRACHY_ACCESSORY'), ('BRACHY_SRC_APP', 'BRACHY_SRC_APP'), ('BRACHY_CHNL_SHLD', 'BRACHY_CHNL_SHLD'), ('SUPPORT', 'SUPPORT'), ('FIXATION', 'FIXATION'), ('DOSE_REGION', 'DOSE_REGION'), ('CONTROL', 'CONTROL'), ('DOSE_MEASUREMENT', 'DOSE_MEASUREMENT')], max_length=256, null=True, verbose_name='Type of the Structure (ROI)')),
                ('roi_display_color', models.CharField(blank=True, max_length=256, null=True, verbose_name='Display Color of the Structure (ROI)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autosegmentation_structure', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.autosegmentationstructure')),
            ],
            options={
                'verbose_name': 'Structure Properties',
                'verbose_name_plural': 'Structure Properties',
            },
        ),
    ]
