# Generated by Django 5.2.10 on 2026-01-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0047_structureproperties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureproperties',
            name='roi_label',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Preferred Name for the Structure (ROI)'),
        ),
    ]
