# Generated by Django 5.2.10 on 2026-02-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0048_alter_structureproperties_roi_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='task1_checkpoint_directories_processed',
            field=models.IntegerField(default=0, help_text='Internal: Number of directories processed in current task1 run'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='task1_checkpoint_last_directory',
            field=models.TextField(blank=True, help_text='Internal: Last processed directory path for task1 checkpoint recovery on network storage', null=True),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='task1_checkpoint_last_updated',
            field=models.DateTimeField(blank=True, help_text='Internal: Last time task1 checkpoint was updated', null=True),
        ),
    ]
