# Generated by Django 5.2.10 on 2026-02-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0049_add_task1_checkpoint_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='export_datetime',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the RT Structure was exported to remote node', null=True),
        ),
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='export_node_name',
            field=models.CharField(blank=True, help_text='Name of the remote node where the RT Structure was exported', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='rtstructurefileimport',
            name='exported_to_remote_node',
            field=models.BooleanField(default=False, help_text='Whether this RT Structure file was exported to a remote DICOM node via C-STORE'),
        ),
    ]
