# Generated by Django 6.0.5 on 2026-06-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0050_add_rtstruct_export_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfileexport',
            name='deidentified_zip_file_transfer_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CHEKSUM_MATCH_FAILED', 'Checksum match failed'), ('INVALID_RT_STRUCT_FILE', 'Invalid RTStructureSet FIle Received'), ('RTSTRUCT_RECEIVED', 'RTStructureSet File Received'), ('TASK_NOT_FOUND', 'Task Not found at Remote Server')], default='PENDING', help_text='Status of the zip file transfer to the DRAW API server', max_length=256, null=True),
        ),
    ]
