# Generated by Django 6.0.5 on 2026-06-05 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0051_alter_dicomfileexport_deidentified_zip_file_transfer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalStructures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roi_label', models.CharField(max_length=256)),
                ('rt_roi_interpreted_type', models.CharField(blank=True, choices=[('EXTERNAL', 'EXTERNAL'), ('PTV', 'PTV'), ('CTV', 'CTV'), ('GTV', 'GTV'), ('TREATED_VOLUME', 'TREATED_VOLUME'), ('IRRAD_VOLUME', 'IRRAD_VOLUME'), ('OAR', 'OAR'), ('BOLUS', 'BOLUS'), ('AVOIDANCE', 'AVOIDANCE'), ('ORGAN', 'ORGAN'), ('MARKER', 'MARKER'), ('REGISTRATION', 'REGISTRATION'), ('ISOCENTER', 'ISOCENTER'), ('CONTRAST_AGENT', 'CONTRAST_AGENT'), ('CAVITY', 'CAVITY'), ('BRACHY_CHANNEL', 'BRACHY_CHANNEL'), ('BRACHY_ACCESSORY', 'BRACHY_ACCESSORY'), ('BRACHY_SRC_APP', 'BRACHY_SRC_APP'), ('BRACHY_CHNL_SHLD', 'BRACHY_CHNL_SHLD'), ('SUPPORT', 'SUPPORT'), ('FIXATION', 'FIXATION'), ('DOSE_REGION', 'DOSE_REGION'), ('CONTROL', 'CONTROL'), ('DOSE_MEASUREMENT', 'DOSE_MEASUREMENT')], max_length=256, null=True, verbose_name='Type of the Structure (ROI)')),
                ('roi_display_color', models.CharField(blank=True, max_length=256, null=True)),
                ('roi_generation_logic', models.CharField(blank=True, help_text='This field will define the logic that will be used for generate the ROI.', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autosegmentation_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dicom_handler.autosegmentationtemplate')),
            ],
            options={
                'verbose_name': 'Additional Structures',
                'verbose_name_plural': 'Additional Structures',
            },
        ),
    ]
