# Generated by Django 6.0.5 on 2026-06-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0052_additionalstructures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalstructures',
            name='roi_generation_logic',
            field=models.JSONField(blank=True, help_text='This field will define the logic that will be used for generate the ROI.', null=True),
        ),
    ]
