# Generated by Django 6.0.5 on 2026-07-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0053_alter_additionalstructures_roi_generation_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='exclude_localizer_series',
            field=models.BooleanField(default=True, help_text='Exclude scanograms, surview, scout or topograms from the series handling process. This is a system wide configuration whcih will prevent these series from being sent for automatic segmentation.'),
        ),
    ]
