# Generated by Django 6.0.8 on 2026-08-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0054_systemconfiguration_exclude_localizer_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='exclude_secondary_capture',
            field=models.BooleanField(default=True, help_text='Exclude secondary capture images from the series handling process based on SOP Class UID. This prevents secondary capture images (which may have CT/MR/PT modality but are not actual diagnostic images) from being sent for automatic segmentation.'),
        ),
    ]
