# Generated by Django 6.0.8 on 2026-09-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_handler', '0055_systemconfiguration_exclude_secondary_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomseries',
            name='station_name',
            field=models.CharField(blank=True, help_text='Station name where the series originated.', max_length=256, null=True),
        ),
    ]
