# Generated by Django 5.2.9 on 2026-01-02 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationAETitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ae_title', models.CharField(help_text='Destination Application Entity Title (max 16 characters).', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_ae_title', message='AE Title must contain only uppercase letters, numbers, underscores, and hyphens.', regex='^[A-Z0-9_\\-]+$')])),
                ('description', models.CharField(blank=True, help_text="Description of this destination (e.g., 'PACS Server', 'Backup Archive').", max_length=255)),
                ('host', models.CharField(help_text='Hostname or IP address of the destination.', max_length=255)),
                ('port', models.IntegerField(default=11112, help_text='Port number of the destination DICOM service.', validators=[django.core.validators.MinValueValidator(1024), django.core.validators.MaxValueValidator(65535)])),
                ('is_active', models.BooleanField(default=True, help_text='Whether this destination is currently available for C-MOVE operations.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Timestamp of last successful C-MOVE to this destination.', null=True)),
            ],
            options={
                'verbose_name': 'Destination AE Title',
                'verbose_name_plural': 'Destination AE Titles',
                'ordering': ['ae_title'],
            },
        ),
        migrations.AlterField(
            model_name='dicomserverconfig',
            name='storage_root_path',
            field=models.CharField(blank=True, help_text='Storage path is automatically set from SystemConfiguration.folder_configuration. This field is optional and will be overridden at runtime.', max_length=512, null=True),
        ),
    ]
