# Generated by Django 5.2.9 on 2026-01-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0002_destinationaetitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomserverconfig',
            name='storage_root_path',
        ),
    ]
