# Generated by Django 5.2.9 on 2026-01-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0003_remove_dicomserverconfig_storage_root_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomserverconfig',
            name='auto_import_to_handler',
        ),
        migrations.RemoveField(
            model_name='dicomserverconfig',
            name='copy_to_handler_folder',
        ),
        migrations.RemoveField(
            model_name='dicomserverconfig',
            name='trigger_processing_chain',
        ),
    ]
