# Generated by Django 5.2.9 on 2026-01-04 06:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0004_remove_dicomserverconfig_auto_import_to_handler_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteDicomNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this DICOM node (e.g., 'Main PACS', 'CT Scanner 1')", max_length=100, unique=True)),
                ('ae_title', models.CharField(help_text='Application Entity Title of the remote DICOM node', max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_ae_title', message='AE Title must contain only uppercase letters, numbers, underscores, and hyphens.', regex='^[A-Z0-9_\\-]+$')])),
                ('host', models.CharField(help_text='Hostname or IP address of the remote DICOM node', max_length=255)),
                ('port', models.IntegerField(help_text='Port number for DICOM communication', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('supports_c_find', models.BooleanField(default=True, help_text='Remote node supports C-FIND (query) operations')),
                ('supports_c_move', models.BooleanField(default=True, help_text='Remote node supports C-MOVE (retrieve) operations')),
                ('supports_c_get', models.BooleanField(default=False, help_text='Remote node supports C-GET (retrieve) operations')),
                ('query_retrieve_model', models.CharField(choices=[('patient', 'Patient Root Query/Retrieve'), ('study', 'Study Root Query/Retrieve'), ('patient_study', 'Patient/Study Only Query/Retrieve')], default='study', help_text='Query/Retrieve Information Model supported by this node', max_length=20)),
                ('timeout', models.IntegerField(default=30, help_text='Connection timeout in seconds', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('max_pdu_size', models.IntegerField(default=16384, help_text='Maximum PDU size in bytes (default: 16384)', validators=[django.core.validators.MinValueValidator(4096), django.core.validators.MaxValueValidator(131072)])),
                ('move_destination_ae', models.CharField(blank=True, help_text='AE Title to use as move destination (usually our local AE title)', max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this node is active and available for queries')),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about this DICOM node')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_successful_connection', models.DateTimeField(blank=True, help_text='Last time a successful connection was made to this node', null=True)),
            ],
            options={
                'verbose_name': 'Remote DICOM Node',
                'verbose_name_plural': 'Remote DICOM Nodes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DicomQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.UUIDField(editable=False, help_text='Unique identifier for this query', unique=True)),
                ('query_level', models.CharField(choices=[('PATIENT', 'Patient Level'), ('STUDY', 'Study Level'), ('SERIES', 'Series Level'), ('IMAGE', 'Image Level')], help_text='DICOM query level (Patient, Study, Series, or Image)', max_length=10)),
                ('query_parameters', models.JSONField(default=dict, help_text='Query parameters as JSON (e.g., PatientID, StudyDate, etc.)')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the query', max_length=20)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned by the query')),
                ('error_message', models.TextField(blank=True, help_text='Error message if query failed')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Query execution time in seconds', null=True)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated this query', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicom_queries', to=settings.AUTH_USER_MODEL)),
                ('remote_node', models.ForeignKey(help_text='Remote DICOM node that was queried', on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='dicom_server.remotedicomnode')),
            ],
            options={
                'verbose_name': 'DICOM Query',
                'verbose_name_plural': 'DICOM Queries',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='DicomQueryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(help_text='Complete DICOM dataset returned as JSON')),
                ('patient_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('study_instance_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_description', models.CharField(blank=True, max_length=255)),
                ('series_instance_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('series_description', models.CharField(blank=True, max_length=255)),
                ('modality', models.CharField(blank=True, max_length=16)),
                ('number_of_instances', models.IntegerField(blank=True, null=True)),
                ('retrieved', models.BooleanField(default=False, help_text='Whether this result has been retrieved')),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(help_text='Query that returned this result', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dicom_server.dicomquery')),
            ],
            options={
                'verbose_name': 'DICOM Query Result',
                'verbose_name_plural': 'DICOM Query Results',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DicomRetrieveJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(editable=False, help_text='Unique identifier for this retrieve job', unique=True)),
                ('retrieve_method', models.CharField(choices=[('C-MOVE', 'C-MOVE'), ('C-GET', 'C-GET')], help_text='Method used for retrieval (C-MOVE or C-GET)', max_length=10)),
                ('retrieve_level', models.CharField(choices=[('STUDY', 'Study Level'), ('SERIES', 'Series Level'), ('IMAGE', 'Image Level')], help_text='Level of retrieval (Study, Series, or Image)', max_length=10)),
                ('study_instance_uid', models.CharField(help_text='Study Instance UID to retrieve', max_length=64)),
                ('series_instance_uid', models.CharField(blank=True, help_text='Series Instance UID to retrieve (if series-level)', max_length=64)),
                ('sop_instance_uid', models.CharField(blank=True, help_text='SOP Instance UID to retrieve (if image-level)', max_length=64)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the retrieve job', max_length=20)),
                ('total_instances', models.IntegerField(default=0, help_text='Total number of instances to retrieve')),
                ('completed_instances', models.IntegerField(default=0, help_text='Number of instances successfully retrieved')),
                ('failed_instances', models.IntegerField(default=0, help_text='Number of instances that failed to retrieve')),
                ('error_message', models.TextField(blank=True, help_text='Error message if retrieve failed')),
                ('duration_seconds', models.FloatField(blank=True, help_text='Total retrieve time in seconds', null=True)),
                ('transfer_speed_mbps', models.FloatField(blank=True, help_text='Average transfer speed in MB/s', null=True)),
                ('destination_path', models.CharField(blank=True, help_text='Local path where retrieved files are stored', max_length=500)),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who initiated this retrieve job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicom_retrieve_jobs', to=settings.AUTH_USER_MODEL)),
                ('query_result', models.ForeignKey(blank=True, help_text='Query result that initiated this retrieve', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieve_jobs', to='dicom_server.dicomqueryresult')),
                ('remote_node', models.ForeignKey(help_text='Remote DICOM node to retrieve from', on_delete=django.db.models.deletion.CASCADE, related_name='retrieve_jobs', to='dicom_server.remotedicomnode')),
            ],
            options={
                'verbose_name': 'DICOM Retrieve Job',
                'verbose_name_plural': 'DICOM Retrieve Jobs',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dicomqueryresult',
            index=models.Index(fields=['patient_id'], name='dicom_serve_patient_2be298_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomqueryresult',
            index=models.Index(fields=['study_instance_uid'], name='dicom_serve_study_i_6aa1ef_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomqueryresult',
            index=models.Index(fields=['series_instance_uid'], name='dicom_serve_series__557a72_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomqueryresult',
            index=models.Index(fields=['study_date'], name='dicom_serve_study_d_529fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomqueryresult',
            index=models.Index(fields=['modality'], name='dicom_serve_modalit_6c42ea_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomretrievejob',
            index=models.Index(fields=['-initiated_at'], name='dicom_serve_initiat_b04708_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomretrievejob',
            index=models.Index(fields=['status'], name='dicom_serve_status_a5d07b_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomretrievejob',
            index=models.Index(fields=['study_instance_uid'], name='dicom_serve_study_i_49f523_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomquery',
            index=models.Index(fields=['-initiated_at'], name='dicom_serve_initiat_b042ae_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomquery',
            index=models.Index(fields=['status'], name='dicom_serve_status_7459a1_idx'),
        ),
        migrations.AddIndex(
            model_name='dicomquery',
            index=models.Index(fields=['query_level'], name='dicom_serve_query_l_b9df52_idx'),
        ),
    ]
