# Generated by Django 5.2.9 on 2026-01-07 01:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0005_remotedicomnode_dicomquery_dicomqueryresult_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationaetitle',
            name='port',
            field=models.IntegerField(default=11112, help_text='Port number of the destination DICOM service.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='dicomserverconfig',
            name='port',
            field=models.IntegerField(default=11112, help_text='Port number for DICOM communication (default: 11112, range: 1024-65535).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
