# Generated by Django 5.2.9 on 2026-01-07 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0006_alter_destinationaetitle_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedicomnode',
            name='allow_incoming',
            field=models.BooleanField(default=False, help_text='Allow this AE title to send DICOM files to our server (C-STORE)'),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='expected_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Expected IP address for incoming connections (optional, for documentation/validation)', null=True),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='last_incoming_connection',
            field=models.DateTimeField(blank=True, help_text='Last time this node successfully sent files to us', null=True),
        ),
        migrations.AlterField(
            model_name='dicomserverconfig',
            name='port',
            field=models.IntegerField(default=11112, help_text='Port number for DICOM communication (default: 11112, range: 1-65535).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='host',
            field=models.CharField(blank=True, help_text='Hostname or IP address of the remote DICOM node (optional for incoming-only nodes)', max_length=255),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this node is active'),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='last_successful_connection',
            field=models.DateTimeField(blank=True, help_text='Last time a successful outgoing connection was made to this node', null=True),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='port',
            field=models.IntegerField(blank=True, help_text='Port number for DICOM communication (optional for incoming-only nodes)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='query_retrieve_model',
            field=models.CharField(blank=True, choices=[('patient', 'Patient Root Query/Retrieve'), ('study', 'Study Root Query/Retrieve'), ('patient_study', 'Patient/Study Only Query/Retrieve')], default='study', help_text='Query/Retrieve Information Model supported by this node', max_length=20),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='supports_c_find',
            field=models.BooleanField(default=False, help_text='Remote node supports C-FIND (query) operations'),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='supports_c_move',
            field=models.BooleanField(default=False, help_text='Remote node supports C-MOVE (retrieve) operations'),
        ),
    ]
