# Generated by Django 5.2.9 on 2026-01-07 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0007_remotedicomnode_allow_incoming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotedicomnode',
            name='ae_title',
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='incoming_ae_title',
            field=models.CharField(blank=True, help_text='AE Title used when this node sends files to us (required if allow_incoming is True)', max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_ae_title', message='AE Title must contain only uppercase letters, numbers, underscores, and hyphens.', regex='^[A-Z0-9_\\-]+$')]),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='outgoing_ae_title',
            field=models.CharField(blank=True, help_text='AE Title used for Query/Retrieve operations (required if any Q/R capability is enabled)', max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_ae_title', message='AE Title must contain only uppercase letters, numbers, underscores, and hyphens.', regex='^[A-Z0-9_\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='allow_incoming',
            field=models.BooleanField(default=False, help_text='Allow this node to send DICOM files to our server (C-STORE)'),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='host',
            field=models.CharField(blank=True, help_text='Hostname or IP address of the remote DICOM node (required for outgoing operations)', max_length=255),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='port',
            field=models.IntegerField(blank=True, help_text='Port number for DICOM communication (required for outgoing operations)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
