# Generated by Django 5.2.9 on 2026-01-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0008_remove_remotedicomnode_ae_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomserverconfig',
            name='notification_email',
        ),
        migrations.RemoveField(
            model_name='dicomserverconfig',
            name='notify_on_error',
        ),
        migrations.RemoveField(
            model_name='dicomserverconfig',
            name='notify_on_receive',
        ),
    ]
