# Generated by Django 5.2.9 on 2026-01-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0009_remove_dicomserverconfig_notification_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomserverconfig',
            name='cached_storage_last_updated',
            field=models.DateTimeField(blank=True, help_text='Timestamp when storage cache was last updated.', null=True),
        ),
        migrations.AddField(
            model_name='dicomserverconfig',
            name='cached_storage_usage_bytes',
            field=models.BigIntegerField(default=0, help_text='Cached storage usage in bytes. Updated periodically to avoid performance issues.'),
        ),
    ]
