# Generated by Django 5.2.9 on 2026-01-08 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0010_dicomserverconfig_cached_storage_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomserverconfig',
            name='max_pdu_size',
            field=models.IntegerField(default=131072, help_text='Maximum Protocol Data Unit size in bytes (default: 131072, range: 4096-131072).', validators=[django.core.validators.MinValueValidator(4096), django.core.validators.MaxValueValidator(131072)]),
        ),
    ]
