# Generated by Django 5.2.9 on 2026-01-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0012_dicomserverconfig_max_query_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomserverconfig',
            name='enable_c_find',
            field=models.BooleanField(default=True, help_text='Enable C-FIND (query) service for Patient/Study/Series level queries.'),
        ),
        migrations.AlterField(
            model_name='dicomserverconfig',
            name='enable_c_get',
            field=models.BooleanField(default=True, help_text='Enable C-GET (retrieve) service to send DICOM files over the same association.'),
        ),
        migrations.AlterField(
            model_name='dicomserverconfig',
            name='enable_c_move',
            field=models.BooleanField(default=True, help_text='Enable C-MOVE (retrieve) service to send DICOM files to remote destinations.'),
        ),
    ]
