# Generated by Django 5.2.10 on 2026-01-14 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0014_alter_dicomserverconfig_max_query_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotedicomnode',
            name='incoming_ae_title',
            field=models.CharField(blank=True, help_text='The AE Title that the remote node uses when sending files to our server (required if allowing incoming connections)', max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_ae_title', message='AE Title must contain only uppercase letters, numbers, underscores, and hyphens.', regex='^[A-Z0-9_\\-]+$')], verbose_name="Remote Node's AE Title (when sending to us)"),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='move_destination_ae',
            field=models.CharField(blank=True, help_text='The AE Title of our local DICOM server. Leave empty to use the default from server configuration.', max_length=16, verbose_name='Our Local AE Title (for receiving files)'),
        ),
        migrations.AlterField(
            model_name='remotedicomnode',
            name='outgoing_ae_title',
            field=models.CharField(blank=True, help_text='The AE Title of the remote node that we use when querying or retrieving files from it (required if enabling Query/Retrieve)', max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_ae_title', message='AE Title must contain only uppercase letters, numbers, underscores, and hyphens.', regex='^[A-Z0-9_\\-]+$')], verbose_name="Remote Node's AE Title (for queries)"),
        ),
    ]
