# Generated by Django 5.2.10 on 2026-01-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0015_alter_remotedicomnode_incoming_ae_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomserverconfig',
            name='storage_limit_exceeded',
            field=models.BooleanField(default=False, help_text='Flag indicating if storage limit has been exceeded. Updated by periodic task.'),
        ),
    ]
