# Generated by Django 5.2.10 on 2026-02-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0016_dicomserverconfig_storage_limit_exceeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedicomnode',
            name='is_export_destination',
            field=models.BooleanField(default=False, help_text='Whether this node is an export destination for exporting RTStructureSet Files after the segmentation has been completed.'),
        ),
    ]
