# Generated by Django 5.2.12 on 2026-03-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0017_remotedicomnode_is_export_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomserverconfig',
            name='copy_to_handler_folder',
            field=models.BooleanField(default=True, help_text='Copy received DICOM files to the DICOM Handler processing folder for chain processing.'),
        ),
        migrations.AddField(
            model_name='dicomserverconfig',
            name='trigger_processing_chain',
            field=models.BooleanField(default=True, help_text='Automatically trigger the DICOM processing chain (Task2→Task3→Task4) for C-STORE received series.'),
        ),
    ]
