# Generated by Django 6.0.5 on 2026-06-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0018_dicomserverconfig_copy_to_handler_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotedicomnode',
            name='fallback_export_destination_priority',
            field=models.PositiveIntegerField(blank=True, help_text='If this is a fallback export destinaton, then select the priority. A lower number indicates a higher priority for the fallback export destination choice.', null=True),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='is_fallback_export_destination',
            field=models.BooleanField(default=False, help_text='Weather this node is the fall back export destination in case the default destination is not reachable.'),
        ),
        migrations.AddField(
            model_name='remotedicomnode',
            name='is_primary_export_destination',
            field=models.BooleanField(default=False, help_text='Weather this node is the default export destionation for RTStructureSet File after segmentation has been completed'),
        ),
    ]
