# Generated by Django 6.0.5 on 2026-06-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dicom_server', '0019_remotedicomnode_fallback_export_destination_priority_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='remotedicomnode',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary_export_destination', False), ('is_export_destination', True), _connector='OR'), name='primary_requires_export_destination', violation_error_message='Primary export destination can only be set if the node is marked as an export destination.'),
        ),
        migrations.AddConstraint(
            model_name='remotedicomnode',
            constraint=models.CheckConstraint(condition=models.Q(('is_fallback_export_destination', False), ('is_export_destination', True), _connector='OR'), name='fallback_requires_export_destination', violation_error_message='Fallback export destination can only be set if the node is marked as an export destination.'),
        ),
        migrations.AddConstraint(
            model_name='remotedicomnode',
            constraint=models.CheckConstraint(condition=models.Q(('is_primary_export_destination', False), ('is_fallback_export_destination', False), _connector='OR'), name='not_both_primary_and_fallback', violation_error_message='A node cannot be both primary and fallback export destination.'),
        ),
    ]
