# Generated by Django 5.2.8 on 2025-11-28 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RTStructureSetFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255, verbose_name='Patient Name in the RT StructureSet File')),
                ('patient_id', models.CharField(max_length=255, verbose_name='Patient ID in the RT StructureSet File')),
                ('study_instance_uid', models.CharField(max_length=255, verbose_name='Study Instance UID for the RT StructureSet File')),
                ('series_instance_uid', models.CharField(max_length=255, verbose_name='Series Instance UID for the RT StructureSet File')),
                ('sop_instance_uid', models.CharField(max_length=255, verbose_name='SOP Instance UID for the RT StructureSet File')),
                ('structure_set_label', models.CharField(max_length=255, verbose_name='StructureSet Label for the RT StructureSet File')),
                ('referenced_series_instance_uid', models.CharField(max_length=255, verbose_name='Referenced Series Instance UID for the RT StructureSet File')),
                ('rtstructure_file', models.FileField(blank=True, null=True, upload_to='rtstruct_files/', verbose_name='RT Structure Set File')),
                ('structure_set_date', models.DateField(blank=True, null=True, verbose_name='Structure Set Date from RT Structure Set File')),
                ('number_of_rois', models.IntegerField(blank=True, null=True, verbose_name='Number of Regions of Interest (Structures) in the RT Structure Set File')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'RT Structure Set File',
                'verbose_name_plural': 'RT Structure Set Files',
                'db_table': 'rt_structure_set_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RTStructureFileComparison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who created this comparison')),
                ('first_rtstructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_rt_structure', to='spatial_overlap.rtstructuresetfile', verbose_name='First RT Structure Set File')),
                ('second_rtstructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_rt_structure', to='spatial_overlap.rtstructuresetfile', verbose_name='Second RT Structure Set File')),
            ],
            options={
                'verbose_name': 'RT Structure File Comparison',
                'verbose_name_plural': 'RT Structure File Comparisons',
                'db_table': 'rt_structure_file_comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparision_type', models.CharField(choices=[('dsc', 'Dice Similarity Coefficient'), ('jsc', 'Jaccard Similarity Coefficient'), ('hd95', 'Hausdorff Distance 95th percentile'), ('msd', 'Mean Surface Distance'), ('apl', 'Added Path Length'), ('mdc', 'Mean Distance to Conformity'), ('umdc', 'Undercontouring Mean Distance to Conformity'), ('omdc', 'Overcontouring Mean Distance to Conformity'), ('voe', 'Volume Overlap Error'), ('vi', 'Variation of Information'), ('cs', 'Cosine Similarity')], max_length=20, verbose_name='Comparison Type')),
                ('result_value', models.FloatField(verbose_name='Result Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spatial_overlap.rtstructurefilecomparison', verbose_name='RT Structure File Comparison')),
            ],
            options={
                'verbose_name': 'RT Structure File Comparison Result',
                'verbose_name_plural': 'RT Structure File Comparison Results',
                'db_table': 'rt_structure_file_comparison_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
