# Generated by Django 5.2.8 on 2025-11-29 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_overlap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtstructuresetfile',
            name='number_of_rois',
        ),
        migrations.CreateModel(
            name='RTStructureSetVOI',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roi_name', models.CharField(max_length=255, verbose_name='ROI Name')),
                ('roi_description', models.CharField(max_length=255, verbose_name='ROI Description')),
                ('roi_volume', models.FloatField(blank=True, null=True, verbose_name='ROI Volume')),
                ('roi_number', models.IntegerField(blank=True, null=True, verbose_name='ROI Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('rtstructure_set_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vois', to='spatial_overlap.rtstructuresetfile', verbose_name='RT Structure Set File')),
            ],
            options={
                'verbose_name': 'RT Structure Set VOI',
                'verbose_name_plural': 'RT Structure Set VOIs',
                'db_table': 'rt_structure_set_vois',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='rtstructurefilecomparison',
            name='first_rtstructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_rt_structure', to='spatial_overlap.rtstructuresetvoi', verbose_name='First RT Structure Set File'),
        ),
        migrations.AlterField(
            model_name='rtstructurefilecomparison',
            name='second_rtstructure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_rt_structure', to='spatial_overlap.rtstructuresetvoi', verbose_name='Second RT Structure Set File'),
        ),
    ]
