# Generated by Django 5.2.8 on 2025-11-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_overlap', '0002_remove_rtstructuresetfile_number_of_rois_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtstructuresetfile',
            name='rtstructure_file',
        ),
        migrations.AddField(
            model_name='rtstructuresetfile',
            name='rtstructure_file_path',
            field=models.FileField(blank=True, null=True, upload_to='rtstruct_files/', verbose_name='RT Structure Set File'),
        ),
        migrations.AddField(
            model_name='rtstructuresetfile',
            name='working_directory',
            field=models.CharField(blank=True, help_text='Directory containing DICOM images and RT Structure files', max_length=512, null=True, verbose_name='Working Directory'),
        ),
    ]
