# Generated by Django 5.2.8 on 2025-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_overlap', '0003_remove_rtstructuresetfile_rtstructure_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtstructuresetfile',
            name='rtstructure_file_path',
            field=models.CharField(blank=True, help_text='Path to RT Structure file in working directory', max_length=512, null=True, verbose_name='RT Structure File Path'),
        ),
    ]
