# Generated by Django 5.2.8 on 2025-11-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_overlap', '0004_alter_rtstructuresetfile_rtstructure_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparisonresult',
            name='comparision_type',
            field=models.CharField(choices=[('dsc', 'Dice Similarity Coefficient'), ('jsc', 'Jaccard Similarity Coefficient'), ('hd95', 'Hausdorff Distance 95th percentile'), ('msd', 'Mean Surface Distance'), ('apl', 'Added Path Length'), ('surface_dsc', 'Surface Dice Similarity Coefficient'), ('mdc', 'Mean Distance to Conformity'), ('umdc', 'Undercontouring Mean Distance to Conformity'), ('omdc', 'Overcontouring Mean Distance to Conformity'), ('voe', 'Volume Overlap Error'), ('vi', 'Variation of Information'), ('cs', 'Cosine Similarity')], max_length=20, verbose_name='Comparison Type'),
        ),
    ]
