# Generated by Django 5.2.8 on 2025-12-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_overlap', '0005_alter_comparisonresult_comparision_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisonresult',
            name='slice_wise_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Data of undercontouring and overcontouring by slice'),
        ),
    ]
